# Generated by Django 2.0.3 on 2018-03-30 13:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('markets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tableid', models.IntegerField()),
                ('category', models.CharField(choices=[('EGG', 'Egg and egg Products'), ('STA', 'Stationary')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField()),
                ('itemName', models.CharField(max_length=100)),
                ('previousPrice', models.IntegerField()),
                ('image', models.ImageField(upload_to='')),
                ('SDP', models.TextField()),
                ('PDC', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('UoM', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('priceType', models.CharField(max_length=10)),
                ('date', models.BigIntegerField()),
                ('remarks', models.CharField(max_length=200)),
                ('locationVerified', models.BooleanField(default=False)),
                ('dataTable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.DataTable')),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='markets.Market')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('accuracy', models.IntegerField()),
                ('latitude', models.IntegerField()),
                ('longitude', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='userLocation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='products.UserLocation'),
        ),
    ]
