# Generated by Django 2.0.3 on 2018-03-30 21:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tableid', models.IntegerField()),
                ('category', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('UoM', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('priceType', models.CharField(max_length=10)),
                ('date', models.BigIntegerField()),
                ('remarks', models.CharField(max_length=200)),
                ('locationVerified', models.BooleanField(default=False)),
                ('marketLocation', models.CharField(max_length=100)),
                ('UserLocation', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ProductCatalogue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField()),
                ('itemName', models.CharField(max_length=100)),
                ('previousPrice', models.IntegerField()),
                ('SDP', models.TextField()),
                ('PDC', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='')),
                ('dataTable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catalogues', to='products.DataTable')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='productCatalogue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.ProductCatalogue'),
        ),
        migrations.AddField(
            model_name='product',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
