# Generated by Django 2.0.3 on 2018-03-30 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pcatid',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
