# Generated by Django 2.0.3 on 2018-03-30 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_pcatid'),
    ]

    operations = [
        migrations.AddField(
            model_name='datatable',
            name='phase',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
