# Generated by Django 2.0.3 on 2018-03-31 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_datatable_phase'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='UoM',
        ),
        migrations.RemoveField(
            model_name='product',
            name='UserLocation',
        ),
        migrations.RemoveField(
            model_name='product',
            name='marketLocation',
        ),
        migrations.RemoveField(
            model_name='product',
            name='quantity',
        ),
        migrations.AddField(
            model_name='productcatalogue',
            name='UoM',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productcatalogue',
            name='quantity',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='priceType',
            field=models.CharField(default='INR', max_length=10),
        ),
        migrations.AlterField(
            model_name='productcatalogue',
            name='image',
            field=models.ImageField(upload_to='media'),
        ),
    ]
