# Generated by Django 2.0.3 on 2018-03-31 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20180331_0822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcatalogue',
            name='image',
            field=models.CharField(max_length=500),
        ),
    ]
