# Generated by Django 2.0.3 on 2018-03-31 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20180331_0825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='remarks',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
