# Generated by Django 2.0.3 on 2018-03-31 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20180331_0902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='remarks',
            field=models.CharField(default=' ', max_length=200),
        ),
    ]
