# Generated by Django 2.0.3 on 2018-03-30 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('location', models.CharField(max_length=30)),
                ('latitude', models.IntegerField()),
                ('longitude', models.IntegerField()),
                ('type', models.CharField(choices=[('UB', 'Urban'), ('RU', 'Rural')], max_length=10)),
            ],
        ),
    ]
